import {createClient} from "@/lib/supabase/server";import type {Claim,Donation,GoodDeed,Innovation,Item,LeaderboardRow,SchoolSettings} from "@/types";
const emptySettings:SchoolSettings={schoolName:"Your School",averageReplacementValue:0,handlingMinutes:0,hourlyStaffCost:0,disposalCost:0,defaultStorageLocation:"",claimInstructions:"Contact your school office for pickup instructions."};
export const isConfigured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
export async function getItems():Promise<Item[]>{const s=await createClient();if(!s)return[];const{data,error}=await s.from("public_items").select("*").order("found_date",{ascending:false});if(error)return[];return(data||[]).map(x=>({id:x.id,itemNumber:x.item_number,category:x.category,color:x.color||undefined,subcategory:x.subcategory,description:x.description,foundDate:x.found_date,foundLocation:x.found_location,publicLocation:x.public_location,condition:x.condition,estimatedValue:Number(x.estimated_value||0),status:x.status,photoUrl:x.photo_url||"/items/placeholder.svg",createdAt:x.created_at}));}
export async function getItem(id:string){return(await getItems()).find(i=>i.id===id)||null;}
export async function getDashboardData(){const s=await createClient();if(!s)return{items:[],claims:[] as Claim[],settings:emptySettings,configured:false};const[{data:items},{data:claims},{data:settings},{data:school}]=await Promise.all([s.from("items").select("*"),s.from("claims").select("*"),s.from("school_settings").select("*").maybeSingle(),s.from("schools").select("name").maybeSingle()]);return{items:(items||[]).map(x=>({id:x.id,itemNumber:x.item_number,category:x.category,color:x.color||undefined,description:x.description,foundDate:x.found_date,foundLocation:x.found_location,publicLocation:x.public_location,storageLocation:x.storage_location,condition:x.condition,estimatedValue:Number(x.estimated_value||0),status:x.status,photoUrl:x.photo_url||"/items/placeholder.svg",internalNotes:x.internal_notes,createdAt:x.created_at,returnedAt:x.returned_at})),claims:(claims||[]).map(x=>({id:x.id,itemId:x.item_id,studentName:x.student_name,studentEmail:x.student_email,identifyingDetails:x.identifying_details,lostDate:x.lost_date,lostLocation:x.lost_location,status:x.status,createdAt:x.created_at})),settings:settings?{schoolName:school?.name||"Your School",averageReplacementValue:Number(settings.average_replacement_value),handlingMinutes:Number(settings.average_handling_minutes),hourlyStaffCost:Number(settings.hourly_staff_cost),disposalCost:Number(settings.estimated_disposal_cost),defaultStorageLocation:settings.default_storage_location||"",claimInstructions:settings.claim_instructions||emptySettings.claimInstructions}:emptySettings,configured:true};}
export async function getDonations():Promise<Donation[]>{const s=await createClient();if(!s)return[];const{data}=await s.from("public_donations").select("*").order("created_at",{ascending:false});return(data||[]).map(x=>({id:x.id,title:x.title,description:x.description,category:x.category,condition:x.condition,photoUrl:x.photo_url,status:x.status,donorName:x.donor_name,createdAt:x.created_at}));}
export async function getGoodDeeds():Promise<GoodDeed[]>{const s=await createClient();if(!s)return[];const{data}=await s.from("good_deeds_feed").select("*").order("created_at",{ascending:false});return(data||[]).map(x=>({id:x.id,studentName:x.student_name,photoUrl:x.photo_url,caption:x.caption,description:x.description,impact:x.impact,lesson:x.lesson,motivation:x.motivation,motivatedBy:x.motivated_by,reactionCount:Number(x.reaction_count||0),createdAt:x.created_at}));}
export async function getInnovations():Promise<Innovation[]>{const s=await createClient();if(!s)return[];const{data}=await s.from("innovation_board").select("*").order("created_at",{ascending:false});return(data||[]).map(x=>({id:x.id,studentName:x.student_name,title:x.title,summary:x.summary,problem:x.problem,skillsNeeded:x.skills_needed||[],teamSize:x.team_size,memberCount:Number(x.member_count||0),status:x.status,createdAt:x.created_at}));}
export async function getLeaderboards(){const s=await createClient();if(!s)return{returns:[] as LeaderboardRow[],donations:[] as LeaderboardRow[],kindness:[] as LeaderboardRow[]};const[{data:returns},{data:donations},{data:kindness}]=await Promise.all([s.from("return_leaderboard").select("*"),s.from("donation_leaderboard").select("*"),s.from("kindness_leaderboard").select("*")]);const map=(rows:Record<string,unknown>[]|null):LeaderboardRow[]=>(rows||[]).map(x=>({studentId:String(x.student_id),studentName:String(x.student_name),avatarUrl:x.avatar_url?String(x.avatar_url):null,score:Number(x.score),count:Number(x.count)}));return{returns:map(returns),donations:map(donations),kindness:map(kindness)};}
