-- Back2Me initial schema. Run in the Supabase SQL editor.
create extension if not exists pgcrypto;
create type public.user_role as enum ('student','staff','admin');
create type public.item_status as enum ('FOUND','CLAIM_PENDING','CLAIM_APPROVED','RETURNED','DONATED','DISPOSED');
create type public.claim_status as enum ('PENDING','APPROVED','REJECTED','COMPLETED');

create table public.schools(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,logo_url text,created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,school_id uuid not null references public.schools(id) on delete cascade,role public.user_role not null default 'student',full_name text,created_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),school_id uuid references public.schools(id) on delete cascade,name text not null,unique(school_id,name));
create table public.locations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,name text not null,is_public boolean not null default true,unique(school_id,name));
create table public.school_settings(school_id uuid primary key references public.schools(id) on delete cascade,average_replacement_value numeric(10,2) not null default 40,average_handling_minutes numeric(8,2) not null default 5,hourly_staff_cost numeric(10,2) not null default 0,estimated_disposal_cost numeric(10,2) not null default 0,default_storage_location text,claim_instructions text,updated_at timestamptz not null default now());
create sequence public.item_number_seq;
create table public.items(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,item_number text not null unique,category text not null,subcategory text,description text not null,photo_url text,found_date date not null,found_location text not null,public_location text not null,storage_location text,condition text not null default 'Good',estimated_value numeric(10,2) not null default 0,status public.item_status not null default 'FOUND',internal_notes text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),returned_at timestamptz,donated_at timestamptz,disposed_at timestamptz);
create table public.claims(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.items(id) on delete cascade,school_id uuid not null references public.schools(id) on delete cascade,student_name text not null,student_email text not null,contact_info text,identifying_details text not null,lost_date date,lost_location text,status public.claim_status not null default 'PENDING',reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.item_events(id uuid primary key default gen_random_uuid(),item_id uuid not null references public.items(id) on delete cascade,event_type text not null,performed_by uuid references public.profiles(id),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index items_school_status_idx on public.items(school_id,status);create index items_found_date_idx on public.items(found_date desc);create index items_search_idx on public.items using gin(to_tsvector('english',description||' '||category||' '||found_location));create index claims_school_status_idx on public.claims(school_id,status);create index events_item_created_idx on public.item_events(item_id,created_at desc);

create or replace view public.public_items with (security_invoker=true) as select id,item_number,category,subcategory,description,photo_url,found_date,found_location,public_location,condition,estimated_value,status,created_at from public.items where status in ('FOUND','CLAIM_PENDING','CLAIM_APPROVED','RETURNED');
revoke all on public.items from anon;
grant select(id,item_number,category,subcategory,description,photo_url,found_date,found_location,public_location,condition,estimated_value,status,created_at) on public.items to anon;
grant select on public.public_items to anon,authenticated;

create or replace function public.current_school_id() returns uuid language sql stable security definer set search_path=public as $$select school_id from profiles where id=auth.uid()$$;
create or replace function public.is_school_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role in ('staff','admin'))$$;
create or replace function public.create_found_item(p_category text,p_subcategory text,p_description text,p_found_date date,p_found_location text,p_public_location text,p_storage_location text,p_condition text,p_estimated_value numeric,p_internal_notes text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_school uuid:=public.current_school_id();v_number text;begin if not public.is_school_staff() then raise exception 'Unauthorized';end if;v_number:='B2M-'||extract(year from current_date)::int||'-'||lpad(nextval('item_number_seq')::text,4,'0');insert into items(school_id,item_number,category,subcategory,description,found_date,found_location,public_location,storage_location,condition,estimated_value,internal_notes,created_by) values(v_school,v_number,p_category,p_subcategory,p_description,p_found_date,p_found_location,p_public_location,p_storage_location,p_condition,p_estimated_value,p_internal_notes,auth.uid()) returning id into v_id;insert into item_events(item_id,event_type,performed_by) values(v_id,'FOUND',auth.uid());return v_id;end$$;
create or replace function public.submit_claim(p_item_id uuid,p_student_name text,p_student_email text,p_contact_info text,p_identifying_details text,p_lost_date date,p_lost_location text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v_school uuid;begin select school_id into v_school from items where id=p_item_id and status in ('FOUND','CLAIM_PENDING','CLAIM_APPROVED');if v_school is null then raise exception 'Item unavailable';end if;insert into claims(item_id,school_id,student_name,student_email,contact_info,identifying_details,lost_date,lost_location) values(p_item_id,v_school,p_student_name,p_student_email,p_contact_info,p_identifying_details,p_lost_date,p_lost_location) returning id into v_id;update items set status='CLAIM_PENDING',updated_at=now() where id=p_item_id and status='FOUND';insert into item_events(item_id,event_type,metadata) values(p_item_id,'CLAIM_SUBMITTED',jsonb_build_object('claim_id',v_id));return v_id;end$$;
grant execute on function public.submit_claim(uuid,text,text,text,text,date,text) to anon,authenticated;

alter table public.schools enable row level security;alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.locations enable row level security;alter table public.school_settings enable row level security;alter table public.items enable row level security;alter table public.claims enable row level security;alter table public.item_events enable row level security;
create policy "public reads safe item records" on public.items for select to anon,authenticated using(status in ('FOUND','CLAIM_PENDING','CLAIM_APPROVED','RETURNED'));
create policy "staff reads school items" on public.items for select to authenticated using(school_id=public.current_school_id() and public.is_school_staff());
create policy "staff manages school items" on public.items for all to authenticated using(school_id=public.current_school_id() and public.is_school_staff()) with check(school_id=public.current_school_id() and public.is_school_staff());
create policy "anyone submits claims" on public.claims for insert to anon,authenticated with check(exists(select 1 from items i where i.id=item_id and i.school_id=claims.school_id and i.status in ('FOUND','CLAIM_PENDING','CLAIM_APPROVED')));
create policy "staff reads school claims" on public.claims for select to authenticated using(school_id=public.current_school_id() and public.is_school_staff());
create policy "staff updates school claims" on public.claims for update to authenticated using(school_id=public.current_school_id() and public.is_school_staff());
create policy "members read own profile" on public.profiles for select to authenticated using(id=auth.uid() or (school_id=public.current_school_id() and public.is_school_staff()));
create policy "staff reads school settings" on public.school_settings for select to authenticated using(school_id=public.current_school_id());
create policy "admins update school settings" on public.school_settings for update to authenticated using(school_id=public.current_school_id() and exists(select 1 from profiles where id=auth.uid() and role='admin'));
create policy "staff reads events" on public.item_events for select to authenticated using(exists(select 1 from items i where i.id=item_id and i.school_id=public.current_school_id()) and public.is_school_staff());
create policy "staff adds events" on public.item_events for insert to authenticated with check(exists(select 1 from items i where i.id=item_id and i.school_id=public.current_school_id()) and public.is_school_staff());
create policy "school metadata visible" on public.schools for select to authenticated using(id=public.current_school_id());create policy "school categories public" on public.categories for select using(true);create policy "school locations public" on public.locations for select using(is_public or (school_id=public.current_school_id() and public.is_school_staff()));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('item-photos','item-photos',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy "public views item photos" on storage.objects for select using(bucket_id='item-photos');
create policy "staff uploads item photos" on storage.objects for insert to authenticated with check(bucket_id='item-photos' and public.is_school_staff() and (storage.foldername(name))[1]=public.current_school_id()::text);
create policy "staff updates item photos" on storage.objects for update to authenticated using(bucket_id='item-photos' and public.is_school_staff() and (storage.foldername(name))[1]=public.current_school_id()::text);
create policy "staff deletes item photos" on storage.objects for delete to authenticated using(bucket_id='item-photos' and public.is_school_staff() and (storage.foldername(name))[1]=public.current_school_id()::text);
