-- Community expansion: donations, kindness stories, innovation teams, parents, and leaderboards.
alter type public.user_role add value if not exists 'parent';
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists grade_level text;
alter table public.profiles add column if not exists leaderboard_opt_in boolean not null default false;
alter table public.items add column if not exists finder_student_id uuid references public.profiles(id);

create type public.moderation_status as enum ('PENDING','APPROVED','REJECTED');
create type public.donation_status as enum ('AVAILABLE','RESERVED','GIVEN');
create type public.innovation_status as enum ('RECRUITING','BUILDING','COMPLETED');
create table public.parent_student_links(parent_id uuid not null references public.profiles(id) on delete cascade,student_id uuid not null references public.profiles(id) on delete cascade,verified_at timestamptz,primary key(parent_id,student_id));
create table public.donations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,donor_id uuid not null references public.profiles(id),title text not null,description text not null,category text not null,condition text not null,photo_url text,status public.donation_status not null default 'AVAILABLE',moderation_status public.moderation_status not null default 'PENDING',recipient_id uuid references public.profiles(id),reserved_at timestamptz,given_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.donation_requests(id uuid primary key default gen_random_uuid(),donation_id uuid not null references public.donations(id) on delete cascade,requester_id uuid not null references public.profiles(id),message text,need_reason text,status public.claim_status not null default 'PENDING',created_at timestamptz not null default now(),unique(donation_id,requester_id));
create table public.good_deeds(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.profiles(id),photo_url text,caption text not null,description text not null,impact text not null,lesson text not null,motivation text not null,motivated_by text,moderation_status public.moderation_status not null default 'PENDING',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.good_deed_reactions(id uuid primary key default gen_random_uuid(),deed_id uuid not null references public.good_deeds(id) on delete cascade,student_id uuid not null references public.profiles(id),reaction text not null check(reaction in ('CLAP','HEART','INSPIRED')),created_at timestamptz not null default now(),unique(deed_id,student_id));
create table public.innovations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.profiles(id),title text not null,summary text not null,problem text not null,solution text not null,skills_needed text[] not null default '{}',team_size integer not null default 4 check(team_size between 2 and 20),status public.innovation_status not null default 'RECRUITING',moderation_status public.moderation_status not null default 'PENDING',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.innovation_members(innovation_id uuid not null references public.innovations(id) on delete cascade,student_id uuid not null references public.profiles(id),role text,status public.claim_status not null default 'PENDING',joined_at timestamptz not null default now(),primary key(innovation_id,student_id));
create table public.impact_points(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null references public.profiles(id),reason text not null,points integer not null check(points between 1 and 100),reference_type text not null,reference_id uuid not null,created_at timestamptz not null default now(),unique(student_id,reference_type,reference_id,reason));
create index donations_school_status_idx on public.donations(school_id,moderation_status,status);create index deeds_school_status_idx on public.good_deeds(school_id,moderation_status,created_at desc);create index innovations_school_status_idx on public.innovations(school_id,moderation_status,status);create index impact_points_student_idx on public.impact_points(school_id,student_id);

create or replace view public.public_donations with (security_invoker=true) as select d.id,d.title,d.description,d.category,d.condition,d.photo_url,d.status,coalesce(p.display_name,'Student donor') donor_name,d.created_at from donations d join profiles p on p.id=d.donor_id where d.moderation_status='APPROVED' and d.status in ('AVAILABLE','RESERVED');
create or replace view public.good_deeds_feed with (security_invoker=true) as select g.id,coalesce(p.display_name,'Student') student_name,g.photo_url,g.caption,g.description,g.impact,g.lesson,g.motivation,g.motivated_by,g.created_at,count(r.id)::int reaction_count from good_deeds g join profiles p on p.id=g.student_id left join good_deed_reactions r on r.deed_id=g.id where g.moderation_status='APPROVED' group by g.id,p.display_name;
create or replace view public.innovation_board with (security_invoker=true) as select i.id,coalesce(p.display_name,'Student innovator') student_name,i.title,i.summary,i.problem,i.skills_needed,i.team_size,i.status,i.created_at,count(m.student_id) filter(where m.status='APPROVED')::int member_count from innovations i join profiles p on p.id=i.student_id left join innovation_members m on m.innovation_id=i.id where i.moderation_status='APPROVED' group by i.id,p.display_name;
create or replace view public.return_leaderboard with (security_invoker=true) as select p.id student_id,p.display_name student_name,p.avatar_url,count(i.id)::int count,count(i.id)::int*10 score from profiles p join items i on i.finder_student_id=p.id and i.status='RETURNED' where p.leaderboard_opt_in group by p.id order by score desc limit 20;
create or replace view public.donation_leaderboard with (security_invoker=true) as select p.id student_id,p.display_name student_name,p.avatar_url,count(d.id)::int count,count(d.id)::int*15 score from profiles p join donations d on d.donor_id=p.id and d.status='GIVEN' where p.leaderboard_opt_in group by p.id order by score desc limit 20;
create or replace view public.kindness_leaderboard with (security_invoker=true) as select p.id student_id,p.display_name student_name,p.avatar_url,count(distinct g.id)::int count,coalesce(sum(ip.points),0)::int score from profiles p left join good_deeds g on g.student_id=p.id and g.moderation_status='APPROVED' left join impact_points ip on ip.student_id=p.id where p.leaderboard_opt_in group by p.id order by score desc limit 20;
alter view public.public_donations set (security_invoker=false);alter view public.good_deeds_feed set (security_invoker=false);alter view public.innovation_board set (security_invoker=false);alter view public.return_leaderboard set (security_invoker=false);alter view public.donation_leaderboard set (security_invoker=false);alter view public.kindness_leaderboard set (security_invoker=false);
grant select on public.public_donations,public.good_deeds_feed,public.innovation_board,public.return_leaderboard,public.donation_leaderboard,public.kindness_leaderboard to anon,authenticated;

alter table public.parent_student_links enable row level security;alter table public.donations enable row level security;alter table public.donation_requests enable row level security;alter table public.good_deeds enable row level security;alter table public.good_deed_reactions enable row level security;alter table public.innovations enable row level security;alter table public.innovation_members enable row level security;alter table public.impact_points enable row level security;
create policy "approved donations visible" on donations for select using(moderation_status='APPROVED' or donor_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "students create donations" on donations for insert to authenticated with check(donor_id=auth.uid() and school_id=current_school_id());create policy "donors manage donations" on donations for update to authenticated using(donor_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));
create policy "requests visible to participants" on donation_requests for select to authenticated using(requester_id=auth.uid() or exists(select 1 from donations d where d.id=donation_id and (d.donor_id=auth.uid() or (d.school_id=current_school_id() and is_school_staff()))));create policy "students request donations" on donation_requests for insert to authenticated with check(requester_id=auth.uid());create policy "donors review requests" on donation_requests for update to authenticated using(exists(select 1 from donations d where d.id=donation_id and (d.donor_id=auth.uid() or (d.school_id=current_school_id() and is_school_staff()))));
create policy "approved deeds visible" on good_deeds for select using(moderation_status='APPROVED' or student_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "students create deeds" on good_deeds for insert to authenticated with check(student_id=auth.uid() and school_id=current_school_id());create policy "owners edit deeds" on good_deeds for update to authenticated using(student_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));
create policy "reactions visible" on good_deed_reactions for select using(true);create policy "students react" on good_deed_reactions for insert to authenticated with check(student_id=auth.uid());create policy "students change reaction" on good_deed_reactions for update to authenticated using(student_id=auth.uid());create policy "students remove reaction" on good_deed_reactions for delete to authenticated using(student_id=auth.uid());
create policy "approved innovations visible" on innovations for select using(moderation_status='APPROVED' or student_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "students propose innovations" on innovations for insert to authenticated with check(student_id=auth.uid() and school_id=current_school_id());create policy "owners manage innovations" on innovations for update to authenticated using(student_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));
create policy "members visible" on innovation_members for select using(true);create policy "students join teams" on innovation_members for insert to authenticated with check(student_id=auth.uid());create policy "leaders review members" on innovation_members for update to authenticated using(exists(select 1 from innovations i where i.id=innovation_id and (i.student_id=auth.uid() or (i.school_id=current_school_id() and is_school_staff()))));
create policy "points visible to school" on impact_points for select to authenticated using(school_id=current_school_id());create policy "staff award points" on impact_points for insert to authenticated with check(school_id=current_school_id() and is_school_staff());
create policy "families see links" on parent_student_links for select to authenticated using(parent_id=auth.uid() or student_id=auth.uid() or is_school_staff());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('community-media','community-media',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy "community media public" on storage.objects for select using(bucket_id='community-media');create policy "students upload community media" on storage.objects for insert to authenticated with check(bucket_id='community-media' and (storage.foldername(name))[1]=current_school_id()::text and (storage.foldername(name))[2]=auth.uid()::text);create policy "owners manage community media" on storage.objects for update to authenticated using(bucket_id='community-media' and (storage.foldername(name))[2]=auth.uid()::text);create policy "owners delete community media" on storage.objects for delete to authenticated using(bucket_id='community-media' and (storage.foldername(name))[2]=auth.uid()::text);
