-- School-led onboarding, enrollment approval, staff invitations, profiles, timelines, and safety reporting.
create type public.account_status as enum ('PENDING','APPROVED','DENIED','BLOCKED');
alter table public.schools add column if not exists is_active boolean not null default true;
alter table public.schools add column if not exists contact_email text;
alter table public.profiles add column if not exists account_status public.account_status not null default 'APPROVED';
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists wall_enabled boolean not null default true;
alter table public.profiles add column if not exists is_blocked boolean not null default false;
alter table public.profiles add column if not exists blocked_reason text;
alter table public.profiles add column if not exists blocked_at timestamptz;

create table public.enrollment_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,student_id uuid not null unique references public.profiles(id) on delete cascade,student_email text not null,student_name text not null,grade_level text,student_identifier text,request_message text,status public.account_status not null default 'PENDING',reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,decision_note text,created_at timestamptz not null default now());
create table public.staff_invites(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,email text not null,role public.user_role not null default 'staff' check(role in ('staff','admin')),token uuid not null default gen_random_uuid() unique,created_by uuid not null references public.profiles(id),expires_at timestamptz not null default(now()+interval '7 days'),accepted_at timestamptz,created_at timestamptz not null default now());
create table public.timeline_posts(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,author_id uuid not null references public.profiles(id) on delete cascade,body text not null check(char_length(body) between 1 and 1000),moderation_status public.moderation_status not null default 'APPROVED',is_hidden boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create type public.report_status as enum ('OPEN','REVIEWING','RESOLVED','DISMISSED');
create table public.safety_reports(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.schools(id) on delete cascade,reporter_id uuid not null references public.profiles(id),target_user_id uuid references public.profiles(id),target_type text not null check(target_type in ('USER','DONATION','GOOD_DEED','INNOVATION','TIMELINE_POST')),target_id uuid,category text not null,description text not null,urgent boolean not null default false,status public.report_status not null default 'OPEN',assigned_to uuid references public.profiles(id),resolution_note text,created_at timestamptz not null default now(),resolved_at timestamptz);
create index enrollment_school_status_idx on public.enrollment_requests(school_id,status,created_at);create index staff_invite_token_idx on public.staff_invites(token);create index timeline_profile_created_idx on public.timeline_posts(profile_id,created_at desc);create index safety_reports_school_status_idx on public.safety_reports(school_id,status,urgent,created_at);

create or replace view public.school_directory as select id,name,slug,logo_url from public.schools where is_active=true;
create or replace view public.profile_directory as select p.id,p.school_id,coalesce(p.display_name,p.full_name,'Community member') display_name,p.avatar_url,p.bio,p.role,p.grade_level,p.wall_enabled,s.name school_name from profiles p join schools s on s.id=p.school_id where p.account_status='APPROVED' and not p.is_blocked and p.school_id=current_school_id();
create or replace view public.timeline_feed as select t.id,t.school_id,t.profile_id,t.body,t.created_at,coalesce(p.display_name,p.full_name,'Community member') author_name from timeline_posts t join profiles p on p.id=t.author_id where not t.is_hidden and t.moderation_status='APPROVED' and p.account_status='APPROVED' and not p.is_blocked and t.school_id=current_school_id();
alter view public.school_directory set (security_invoker=false);alter view public.profile_directory set (security_invoker=false);alter view public.timeline_feed set (security_invoker=false);
grant select on public.school_directory to anon,authenticated;grant select on public.profile_directory,public.timeline_feed to authenticated;

create or replace function public.is_active_member() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and account_status='APPROVED' and not is_blocked)$$;
create or replace function public.is_school_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role in ('staff','admin') and account_status='APPROVED' and not is_blocked)$$;

create or replace function public.handle_new_account() returns trigger language plpgsql security definer set search_path=public as $$declare v_type text:=new.raw_user_meta_data->>'account_type';v_school uuid;v_invite staff_invites%rowtype;begin
if v_type='school' then insert into schools(name,slug,contact_email) values(trim(new.raw_user_meta_data->>'school_name'),lower(trim(new.raw_user_meta_data->>'school_slug')),new.email) returning id into v_school;insert into school_settings(school_id) values(v_school);insert into profiles(id,school_id,role,full_name,display_name,account_status) values(new.id,v_school,'admin',new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'full_name','APPROVED');
elsif v_type='student' then v_school:=(new.raw_user_meta_data->>'school_id')::uuid;if not exists(select 1 from schools where id=v_school and is_active) then raise exception 'School unavailable';end if;insert into profiles(id,school_id,role,full_name,display_name,grade_level,account_status) values(new.id,v_school,'student',new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'grade_level','PENDING');insert into enrollment_requests(school_id,student_id,student_email,student_name,grade_level,student_identifier,request_message) values(v_school,new.id,new.email,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'grade_level',new.raw_user_meta_data->>'student_identifier',new.raw_user_meta_data->>'request_message');
elsif v_type='staff_invite' then select * into v_invite from staff_invites where token=(new.raw_user_meta_data->>'invite_token')::uuid and lower(email)=lower(new.email) and accepted_at is null and expires_at>now() for update;if v_invite.id is null then raise exception 'Invalid or expired invitation';end if;insert into profiles(id,school_id,role,full_name,display_name,account_status) values(new.id,v_invite.school_id,v_invite.role,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'full_name','APPROVED');update staff_invites set accepted_at=now() where id=v_invite.id;
else raise exception 'Choose a valid Back2Me account type';end if;return new;end$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_account();

alter table public.enrollment_requests enable row level security;alter table public.staff_invites enable row level security;alter table public.timeline_posts enable row level security;alter table public.safety_reports enable row level security;
create policy "student sees own enrollment" on enrollment_requests for select to authenticated using(student_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "staff reviews enrollment" on enrollment_requests for update to authenticated using(school_id=current_school_id() and is_school_staff());
create policy "staff views invites" on staff_invites for select to authenticated using(school_id=current_school_id() and is_school_staff());create policy "admins create invites" on staff_invites for insert to authenticated with check(school_id=current_school_id() and exists(select 1 from profiles where id=auth.uid() and role='admin' and account_status='APPROVED' and not is_blocked));create policy "admins revoke invites" on staff_invites for delete to authenticated using(school_id=current_school_id() and exists(select 1 from profiles where id=auth.uid() and role='admin' and account_status='APPROVED' and not is_blocked));
create policy "school reads visible timelines" on timeline_posts for select to authenticated using(school_id=current_school_id() and not is_hidden and moderation_status='APPROVED');create policy "members write enabled walls" on timeline_posts for insert to authenticated with check(author_id=auth.uid() and school_id=current_school_id() and is_active_member() and exists(select 1 from profiles p where p.id=profile_id and p.school_id=current_school_id() and (p.wall_enabled or p.id=auth.uid())));create policy "authors delete posts" on timeline_posts for delete to authenticated using(author_id=auth.uid() or profile_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "staff moderates timelines" on timeline_posts for update to authenticated using(school_id=current_school_id() and is_school_staff());
create policy "reporters see own reports" on safety_reports for select to authenticated using(reporter_id=auth.uid() or (school_id=current_school_id() and is_school_staff()));create policy "active members report" on safety_reports for insert to authenticated with check(reporter_id=auth.uid() and school_id=current_school_id() and is_active_member());create policy "staff resolves reports" on safety_reports for update to authenticated using(school_id=current_school_id() and is_school_staff());

create or replace function public.review_enrollment(p_request_id uuid,p_decision public.account_status,p_note text default null) returns void language plpgsql security definer set search_path=public as $$declare v_student uuid;begin if not is_school_staff() or p_decision not in ('APPROVED','DENIED') then raise exception 'Unauthorized';end if;select student_id into v_student from enrollment_requests where id=p_request_id and school_id=current_school_id() and status='PENDING' for update;if v_student is null then raise exception 'Request unavailable';end if;update enrollment_requests set status=p_decision,decision_note=p_note,reviewed_by=auth.uid(),reviewed_at=now() where id=p_request_id;update profiles set account_status=p_decision where id=v_student;end$$;
alter table public.good_deeds add column if not exists is_hidden boolean not null default false;
alter table public.donations add column if not exists is_hidden boolean not null default false;
alter table public.innovations add column if not exists is_hidden boolean not null default false;
create or replace function public.block_school_member(p_student_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$begin if not is_school_staff() then raise exception 'Unauthorized';end if;if not exists(select 1 from profiles where id=p_student_id and school_id=current_school_id() and role='student') then raise exception 'Student unavailable';end if;update profiles set is_blocked=true,account_status='BLOCKED',blocked_reason=p_reason,blocked_at=now() where id=p_student_id;update good_deeds set is_hidden=true where student_id=p_student_id;update donations set moderation_status='REJECTED' where donor_id=p_student_id and status='AVAILABLE';update innovations set moderation_status='REJECTED' where student_id=p_student_id;update timeline_posts set is_hidden=true where author_id=p_student_id;end$$;
grant execute on function public.review_enrollment(uuid,public.account_status,text) to authenticated;grant execute on function public.block_school_member(uuid,text) to authenticated;
create policy "staff deletes school donations" on donations for delete to authenticated using(school_id=current_school_id() and is_school_staff());
create policy "staff deletes school deeds" on good_deeds for delete to authenticated using(school_id=current_school_id() and is_school_staff());
create policy "staff deletes school innovations" on innovations for delete to authenticated using(school_id=current_school_id() and is_school_staff());
drop policy if exists "students create donations" on donations;create policy "active students create donations" on donations for insert to authenticated with check(donor_id=auth.uid() and school_id=current_school_id() and is_active_member());
drop policy if exists "students request donations" on donation_requests;create policy "active students request donations" on donation_requests for insert to authenticated with check(requester_id=auth.uid() and is_active_member());
drop policy if exists "students create deeds" on good_deeds;create policy "active students create deeds" on good_deeds for insert to authenticated with check(student_id=auth.uid() and school_id=current_school_id() and is_active_member());
drop policy if exists "students react" on good_deed_reactions;create policy "active students react" on good_deed_reactions for insert to authenticated with check(student_id=auth.uid() and is_active_member());
drop policy if exists "students propose innovations" on innovations;create policy "active students propose innovations" on innovations for insert to authenticated with check(student_id=auth.uid() and school_id=current_school_id() and is_active_member());
drop policy if exists "students join teams" on innovation_members;create policy "active students join teams" on innovation_members for insert to authenticated with check(student_id=auth.uid() and is_active_member());

alter table public.good_deeds add column if not exists is_hidden boolean not null default false;
alter table public.donations add column if not exists is_hidden boolean not null default false;
alter table public.innovations add column if not exists is_hidden boolean not null default false;
create or replace view public.public_donations as select d.id,d.title,d.description,d.category,d.condition,d.photo_url,d.status,coalesce(p.display_name,'Student donor') donor_name,d.created_at from donations d join profiles p on p.id=d.donor_id where d.school_id=current_school_id() and d.moderation_status='APPROVED' and not d.is_hidden and d.status in ('AVAILABLE','RESERVED') and p.account_status='APPROVED' and not p.is_blocked;
create or replace view public.good_deeds_feed as select g.id,coalesce(p.display_name,'Student') student_name,g.photo_url,g.caption,g.description,g.impact,g.lesson,g.motivation,g.motivated_by,g.created_at,count(r.id)::int reaction_count from good_deeds g join profiles p on p.id=g.student_id left join good_deed_reactions r on r.deed_id=g.id where g.school_id=current_school_id() and g.moderation_status='APPROVED' and not g.is_hidden and p.account_status='APPROVED' and not p.is_blocked group by g.id,p.display_name;
create or replace view public.innovation_board as select i.id,coalesce(p.display_name,'Student innovator') student_name,i.title,i.summary,i.problem,i.skills_needed,i.team_size,i.status,i.created_at,count(m.student_id) filter(where m.status='APPROVED')::int member_count from innovations i join profiles p on p.id=i.student_id left join innovation_members m on m.innovation_id=i.id where i.school_id=current_school_id() and i.moderation_status='APPROVED' and not i.is_hidden and p.account_status='APPROVED' and not p.is_blocked group by i.id,p.display_name;
alter view public.public_donations set (security_invoker=false);alter view public.good_deeds_feed set (security_invoker=false);alter view public.innovation_board set (security_invoker=false);

create or replace view public.return_leaderboard with (security_invoker=false) as select p.id student_id,p.display_name student_name,p.avatar_url,count(i.id)::int count,count(i.id)::int*10 score from profiles p join items i on i.finder_student_id=p.id and i.status='RETURNED' where p.school_id=current_school_id() and p.leaderboard_opt_in and p.account_status='APPROVED' and not p.is_blocked group by p.id order by score desc limit 20;
create or replace view public.donation_leaderboard with (security_invoker=false) as select p.id student_id,p.display_name student_name,p.avatar_url,count(d.id)::int count,count(d.id)::int*15 score from profiles p join donations d on d.donor_id=p.id and d.status='GIVEN' where p.school_id=current_school_id() and p.leaderboard_opt_in and p.account_status='APPROVED' and not p.is_blocked group by p.id order by score desc limit 20;
create or replace view public.kindness_leaderboard with (security_invoker=false) as select p.id student_id,p.display_name student_name,p.avatar_url,count(distinct g.id)::int count,coalesce(sum(ip.points),0)::int score from profiles p left join good_deeds g on g.student_id=p.id and g.moderation_status='APPROVED' and not g.is_hidden left join impact_points ip on ip.student_id=p.id where p.school_id=current_school_id() and p.leaderboard_opt_in and p.account_status='APPROVED' and not p.is_blocked group by p.id order by score desc limit 20;
grant select on public.return_leaderboard,public.donation_leaderboard,public.kindness_leaderboard to authenticated;
